name: Maven Deploy Artifact

on:
  push:
    branches:
      - 'master'

jobs:
  build-and-deploy:
    uses: valitydev/base-workflow/.github/workflows/maven-swag-deploy.yml@v2-beta
    secrets:
      server-username: ${{ secrets.OSSRH_USERNAME }}
      server-password: ${{ secrets.OSSRH_TOKEN }}
      deploy-secret-key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
      deploy-secret-key-password: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
      github-token: ${{ secrets.GITHUB_TOKEN }}
      mm-webhook-url: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
